### ISSUE TITLE
QGIS - forms character set 

### ISSUE THREAD

**Issue by jpdupuy** [teksi/district_heating#14]
The attribut comment (mouse over) in QGIS does not seem to be correctly taken into account for special character (é, à, ä, ...)
![QGIS_forms_character_set](https://github.com/teksi/district_heating/assets/72449015/4eb70ab4-2f91-4b8c-86cf-bd4d85825c5d)

**Comment by jpdupuy** [comment]
![QGIS_forms_character_set_2](https://github.com/teksi/district_heating/assets/72449015/83625550-c48e-470e-9f8d-bdc7b65fa5a2)

**Comment by sjib** [comment]
@jpdupuy Can you check the layer encoding in QGIS? Is it set to UTF-8?

![20240515_layer_encoding](https://github.com/teksi/district_heating/assets/1265865/10a415ae-b080-425c-8baf-6a2ecd90f4be)

How about the data in postgres? Is it correctly visible in pg_admin?

Else there is a QGIS tool to change the layer encoding
https://docs.qgis.org/3.34/de/docs/user_manual/processing_algs/qgis/vectorgeneral.html#set-layer-encoding
![20240515_layercodierung_setzen](https://github.com/teksi/district_heating/assets/1265865/153df463-7bd2-47f7-912e-1136cc03b9f5)

@ponceta Any other hints?

**Comment by jpdupuy** [comment]
No, it is incorrect in pgadmin
COMMENT ON COLUMN tdh_od.structure.network_area
    IS ' / Ortsbezeichnung / dÃ©signation du lieu';

I believe th character set was not properly set in the setup_windows.cmd (copy of the setup.sh)

**Comment by jpdupuy** [comment]
![QGIS_Layer_general_encoding](https://github.com/teksi/district_heating/assets/72449015/7886c065-2b06-424a-90d2-d9d3097c1a3f)

**Comment by jpdupuy** [comment]
I had to add the following commands in the setup file  
SET PGCLIENTENCODING=utf-8
chcp 65001
It has solved this issue when I check the SQL description qith PGADMIN
COMMENT ON COLUMN tdh_od.structure.geometry_geometry
    IS ' / offener oder geschlossener Linienzug, Stützpunkte in Landeskoordinaten / polyligne ouverte ou fermée avec des points d’appui en coordonnées nationales';

**Comment by sjib** [comment]
@jpdupuy Can you send me your setup for windows, then I will add it to github.
