### ISSUE TITLE
QGIS generates 2 distinct tables for 2D and 3D

### ISSUE THREAD

**Issue by jpdupuy** [teksi/district_heating#15]
Whenever the data model includes 2 geometry columns (ie for 2D and for 3D) for a specific table :
ALTER TABLE tdh_od.structure ADD COLUMN geometry_geometry geometry('CURVEPOLYGON', :SRID);
ALTER TABLE tdh_od.structure ADD COLUMN geometry3d_geometry geometry('CURVEPOLYGONZ', :SRID);
the QGIS Data manager will propose 2 tables with the same name to import in the canvas
![image](https://github.com/teksi/district_heating/assets/72449015/7443f12a-4e82-4f6a-8516-a02830e893a8)

Therefor, only one geometry column should be specified in the datamodel to avoid confusion (to be discussed)

**Comment by sjib** [comment]
Changed to only one geometry3d - see https://github.com/teksi/district_heating/pull/1/commits/ecaab5c1d59448a01b669991e1a6572966c38547
