### ISSUE TITLE
value list pipe_point_normal_kind : set inactiv values

### ISSUE THREAD

**Issue by jpdupuy** [teksi/district_heating#16]
Since Troncon_statique and troncon_hydraulique (nor noeud_statique and noeud_hydraulique) are not part of the first version, i believe that the value lists should set to inactive the related values armatures.point_statique.<value> (ie: from 8136 to 8146)

![QGIS_pipe_point_normal_kind](https://github.com/teksi/district_heating/assets/72449015/bd1100fa-dc55-40e9-9b86-d9d567cb3453)

**Comment by sjib** [comment]
see also https://github.com/teksi/district_heating/issues/19

**Comment by sjib** [comment]
@jpdupuy You can do this with the following quey:

```
UPDATE tdh_vl.pipe_point_normal_kind
SET active = false
WHERE value_en LIKE '%static_point%';
```

**Comment by jpdupuy** [comment]
@sjib ok, understood, thanks
