### ISSUE TITLE
Setup.sh - duplicate psql import 

### ISSUE THREAD

**Issue by jpdupuy** [teksi/district_heating#17]
03_tdh_db_sia405.sql   and 09_tdh_dictionaries.sql have the same content.
Which one should be used in the setup.sh file ?

**Comment by sjib** [comment]
Both, I have to change the content of 09_*

**Comment by sjib** [comment]
@jpdupuy Is adapted see https://github.com/teksi/district_heating/issues/18#issuecomment-2117443976
