### ISSUE TITLE
QGIS : cannot add pipe_point

### ISSUE THREAD

**Issue by jpdupuy** [teksi/district_heating#18]
Impossible de valider les changements pour la couche point de conduite

Erreurs : ERROR: 1 feature(s) not added.
  
Erreur du fournisseur de données :
      Erreur PostGIS lors de l'ajout d'entité : ERROR:  relation "tdh_sys.dictionary_od_table" does not exist
    LINE 1: ...ELECT shortcut_en                            FROM tdh_sys.di...
                                                                 ^
    QUERY:  SELECT shortcut_en                            FROM tdh_sys.dictionary_od_table WHERE tablename = table_name
    CONTEXT:  PL/pgSQL function tdh_sys.generate_oid(text,text) line 22 at SQL statement

**Comment by sjib** [comment]
@jpdupuy This is cause of the wrong dictionary file - should be updated now 

[new 09_tdh_dictionaries.sql](https://github.com/teksi/district_heating/pull/1/commits/507a1e41bcb6ca43e6340e0b7183e419086f54c3)
[09_tdh_control_cable_dictionaries](https://github.com/teksi/district_heating/pull/1/commits/ee8f2f1c42049209ba4cfe08e84ab48538283524)
The later has to be also added in the setup:
[add 09_tdh_control_cable_dictionaries to setup](https://github.com/teksi/district_heating/pull/1/commits/e5c1b9266713034e41620e660a9916987108a426)
