### ISSUE TITLE
09_tdh_dictionaries.sql : "tdh_od.plantype" does not exist

### ISSUE THREAD

**Issue by jpdupuy** [teksi/district_heating#21]
psql:09_tdh_dictionaries.sql:52: NOTICE:  type "tdh_od.plantype" does not exist

**Comment by sjib** [comment]
@jpdupuy This is correct and only a `NOTICE`, not an `ERROR`
and because of line 52
`DROP TYPE IF EXISTS tdh_od.plantype;`

We drop the TYPE first to be sure it is (re-)created. If it does not exist the NOTICE: type "tdh_od.plantype" does not exist will be displayed.
