### ISSUE TITLE
Editable views for QGIS pipe_point_normal and pipe_point_feed

### ISSUE THREAD

**Issue by jpdupuy** [teksi/district_heating#22]
[0001_views.zip](https://github.com/teksi/district_heating/files/15429010/0001_views.zip)
I fixed the temporary views according to the changes in the datamodel
But I shall need the final editable views for the QGIS project file

**Comment by sjib** [comment]
> But I shall need the final editable views for the QGIS project file
@jpdupuy What do you mean with that?

**Comment by sjib** [comment]
@jpdupuy These viewswith all needed triggers will be generated automatically once the CI is working: see https://github.com/teksi/district_heating/blob/d147e1dfa3e19ff506963f3782c2469f12ce02de/datamodel/app/create_app.py#L79

**Comment by jpdupuy** [comment]
Thanks for the implementation. I tested it and it works fine.

**Comment by sjib** [comment]
The two views vw_pipe_profile_normal and vw_pipe_profile_feed can now be replaced with vw_tdh_pipe_point - see https://github.com/teksi/district_heating/pull/79
