### ISSUE TITLE
Migration importing data in pipe_point and subclasses

### ISSUE THREAD

**Issue by sjib** [teksi/district_heating#27]
@jpdupuy 
Here the code as discussed for your migration:

--- Add additional DEREFERABLE constraints to data model

 ![20240527_oorel_od_pipe_point_feed_pipe_point](https://github.com/teksi/district_heating/assets/1265865/736ba6a7-9d47-46cb-8472-1cabd5bf512e)

`ALTER TABLE tdh_od.pipe_point_feed ALTER CONSTRAINT oorel_od_pipe_point_feed_pipe_point DEFERRABLE INITIALLY DEFERRED;`
`ALTER TABLE tdh_od.pipe_point_norma ALTER CONSTRAINT oorel_od_pipe_point_norma_pipe_point DEFERRABLE INITIALLY DEFERRED;`

And maybe add in FME this call before the whole import or do it manually before running the import:
`SET CONSTRAINTS ALL DEFERRED;`

and then set back at the end

**Comment by jpdupuy** [comment]
@sjib 
ALTER TABLE tdh_od.pipe_point_normal ALTER CONSTRAINT oorel_od_pipe_point_normal_pipe_point DEFERRABLE INITIALLY DEFERRED

I followed your instructions, but did have any success 👎 with fme (also run set constraints all deferred (sql to run before write) 
Bulk copy failed on table 'tdh_od.trench_line' using delimiter ':'. Error was 'ERROR:  insert or update on table "trench_line" violates foreign key constraint "rel_trench_line_trench"
DETAIL:  Key (fk_trench)=(1) is not present in table "trench".

**Comment by sjib** [comment]
@jpdupuy This is not the problem of pipe_point subclasses anymore (?) but of **trench_line.fk_trench**
You have to set DEFERRABLE INITIALLY DEFERRED for that relation also.
If this is a new error then the first step was a success.

**Comment by sjib** [comment]
If this is successful I can add DEFERRABLE INITIALLY DEFERRED to all relations as with tww

**Comment by jpdupuy** [comment]
@sjib Yes, it was successful, thanks
