### ISSUE TITLE
PIPE_POINT_FEED : attributes  year_of_* types (dates)

### ISSUE THREAD

**Issue by jpdupuy** [teksi/district_heating#37]
Hello,

There is a mismatch between the date type defined in the SIA-405 documentation and the implementation 
     start_year smallint,
    reconstruction smallint,
![TEKSI_CAD_pipe_point_feed_datefromat](https://github.com/teksi/district_heating/assets/72449015/afcf51fa-4bce-4bc3-a9e0-ff1b8c5e0acd)

**Comment by jpdupuy** [comment]
I would prefer the year. I am not sure that the operators knows the exact date YYYMMDD.

I have checked in QGEP datamodel, the name of the attribut is year_of_construction. / year_of_replacement / year_of_service
I believe this should be consistant through all products (TWW, TDH, ...)

**Comment by sjib** [comment]
It is implemented as in the INTERLIS - so we go with that:

```
CLASS Point_de_conduite_alimentation EXTENDS Point_de_conduite =  
!! 
  ATTRIBUTE
    Genre: (        
      alimentation_du_reseau,
      derivation,
      poste_de_raccordement,
      autre
    );
    Puissance_abonnee: MANDATORY Kilowatt;
    Puissance_installee: MANDATORY Kilowatt;
    Valeur_diaphragme: MANDATORY Kilowatt;
    Q_abonnee: MANDATORY 0.000 .. 9999.999 [SIA405_Base_f.m3h];
    Categorie: (        
      MI,  !! Maison individuelle
      IL,  !! immeuble
      hopital,
      batiments_publics,
      prestataire_de_services,
      artisanat_industrie,
      clients_speciaux
    );
    Mise_en_service: MANDATORY SIA405_Base_f.Annee;
    Transformation: MANDATORY SIA405_Base_f.Annee;
    Pression: MANDATORY Pression;  !! pression de construction primaire [bar]
    Temperature_aller: MANDATORY Temperature;  !! température
    Temperature_retour: MANDATORY Temperature;  !! température
    Volume_chauffe: MANDATORY 0 .. 9999 [Units.m3];
    Chaleur_consommee: MANDATORY 0 .. 9999999999 [Units.kWh];  !! par année
    Puissance: MANDATORY Kilowatt;
END Point_de_conduite_alimentation;
```

**Comment by sjib** [comment]
I will rename 

- [ ] year_start to year_of_commissioning
- [ ] reconstruction to year_of_reconstruction

**Comment by sjib** [comment]
@jpdupuy Is merged!
