### ISSUE TITLE
Support several geometry types for lines  (pipe_section, cables) and for polygons (structure, trench)

### ISSUE THREAD

**Issue by jpdupuy** [teksi/district_heating#39]
The current defintion prevents FME to import geopackage data id the geometry constraint is based on a unique geometry type
ALTER TABLE tdh_od.pipe_section ADD COLUMN geometry3d_geometry geometry('COMPOUNDCURVEZ', :SRID);
ALTER TABLE tdh_od.structure ADD COLUMN geometry3d_geometry geometry('CURVEPOLYGONZ', :SRID);

Whenever the geopackage is made of strait lines (Linestring) or strait lines + arcs (compoundcurve) fme stops with a fatal error :
ERROR |Bulk copy failed on table 'tdh_od.pipe_section' using delimiter ':'. Error was 'ERROR:  Geometry type (LineString) does not match column type (CompoundCurve)
CONTEXT:  COPY pipe_section, line 1, column geometry3d_geometry: "01020000A008080000030000009AB114071E4843411E47ECD42A8F31...'
ERROR |POSTGIS writer: An error has occurred. Check the logfile above for details

I could not find a solution to solve this issue (The ArcStrocker would transform arcs into line segments, but you would have to change the constraint to a LINESTRINGZ in the datamodel).

I suggest to add the following constraints 
ALTER TABLE tdh_od.pipe_section ADD COLUMN geometry3d_geometry geometry('GEOMETRYZ', :SRID);
ALTER TABLE tdh_od.pipe_section  ADD CONSTRAINT enforce_pipe_section_geotype_geometry3d 
                CHECK (geometrytype(geometry3d_geometry) = 'LINESTRING'::TEXT OR geometrytype(geometry3d_geometry) = 'COMPOUNDCURVE'::TEXT
                OR     geometrytype(geometry3d_geometry) = 'LINESTRINGZ'::TEXT OR geometrytype(geometry3d_geometry) = 'COMPOUNDCURVEZ'::TEXT);	

ALTER TABLE tdh_od.sia405cc_cable  ADD COLUMN geometry3d_geometry geometry('GEOMETRYZ', :SRID);
ALTER TABLE tdh_od.sia405cc_cable  ADD CONSTRAINT enforce_cable_geotype_geometry3d 
                CHECK (geometrytype(geometry3d_geometry) = 'LINESTRING'::TEXT OR geometrytype(geometry3d_geometry) = 'COMPOUNDCURVE'::TEXT
                OR     geometrytype(geometry3d_geometry) = 'LINESTRINGZ'::TEXT OR geometrytype(geometry3d_geometry) = 'COMPOUNDCURVEZ'::TEXT);

ALTER TABLE tdh_od.structure  ADD COLUMN geometry3d_geometry geometry('GEOMETRYZ', :SRID); 
ALTER TABLE tdh_od.structure  ADD CONSTRAINT enforce_structure_geotype_geometry3d
                CHECK (geometrytype(geometry3d_geometry) = 'POLYGON'::TEXT OR geometrytype(geometry3d_geometry) = 'CURVEPOLYGON'::TEXT				
                OR     geometrytype(geometry3d_geometry) = 'POLYGONZ'::TEXT OR geometrytype(geometry3d_geometry) = 'CURVEPOLYGONZ'::TEXT);
Please find a zip file to reproduce the error 
[fme_scripts.zip](https://github.com/user-attachments/files/15587618/fme_scripts.zip)

**Comment by ponceta** [comment]
![image](https://github.com/user-attachments/assets/a02886a8-da20-4209-9b45-5559d80f28d8)

Update writer and add the destination format as compoundcurve (FME will handle 2D 3D automatically)

![image](https://github.com/user-attachments/assets/9d5ba885-b420-4fa1-9cfc-91feaac72420)

**Comment by jpdupuy** [comment]
Thanks, it works fine now. When updating the writer, do not forget to uncheck "Create Generic Spatial Column" and geometry column name=geometry3d_geometry
