### ISSUE TITLE
pipe_point_normal.kind : translation french to english (vanne or soupape) -> (valve)

### ISSUE THREAD

**Issue by jpdupuy** [teksi/district_heating#41]
the translation from french to english is the same for vanne and soupape which makes the legend difficult to understand
![TDH-pipe_point_symbology](https://github.com/teksi/district_heating/assets/72449015/f4451584-ab99-4a74-a7ac-14d2476048cf)

**Comment by sjib** [comment]
Ok, I will correct that

**Comment by ponceta** [comment]
Symbol is the same too so this will maybe need a update on symbology as well?

**Comment by sjib** [comment]
@jpdupuy and @ponceta  I suggest to use `gate_valve` for `vanne` and `valve` for `soupape`

| German  | French  |  English | comment  | comment | commentaire |
|---|---|---|---|---|---|
| Schieber  | vanne  | gate valve | https://de.wikipedia.org/wiki/Absperrschieber  | https://en.wikipedia.org/wiki/Gate_valve  | https://fr.wikipedia.org/wiki/Vanne_d%27arr%C3%AAt |
| Ventil | soupape | valve | https://de.wikipedia.org/wiki/Ventil  | https://en.wikipedia.org/wiki/Valve  | https://fr.wikipedia.org/wiki/Soupape  |

Was ist eigentlich der Unterschied zwischen Hahn, Ventil, Klappe und Schieber?
https://www.ikz.de/ikz-praxis-archiv/p0209/020903.php

Can you confirm?

**Comment by sjib** [comment]
@jpdupuy Can you review the two pull request concerning translations so I can merge them afterwards?

**Comment by jpdupuy** [comment]
@sjib Fine, you can merge this

**Comment by sjib** [comment]
@jpdupuy Is merged!
